CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[FirstName] VARCHAR(50) NOT NULL, 
	[LastName] VARCHAR(50) NOT NULL, 
	[ChangeId] INT NULL, 
	CONSTRAINT [FK_Users_Changes] FOREIGN KEY (ChangeId) REFERENCES Changes([Id])
)
